### ISSUE TITLE
Handle non-existing images (404)

### ISSUE THREAD

**Issue by Skovvart** [vnbaaij/ImageProcessor.Web.Episerver#1]
The FileBlobCache assumes that the requested image exists, resulting in an null-pointer exception being thrown when trying to resolve the blobFolder. A check should be added to ensure that this does not happen. Suggestion:

Update https://github.com/vnbaaij/ImageProcessor.Web.Episerver/blob/master/src/ImageProcessor.Web.Episerver/FileBlobCache.cs#L114

    string blobFolder = blob.BinaryDataContainer.Segments[1];

to

    string blobFolder = blob?.BinaryDataContainer?.Segments[1];
    // Return true to bypass cache by marking it as "new or updated" when not found
    if (blobFolder == null) return true;

It may also need the following change to ImageService

Update

    public async Task<byte[]> GetImage(object id)
    {
        var content = ContentRouteHelper.Service.Content;

        if (content != null && content.QueryDistinctAccess(AccessLevel.Read))
        {
            if (content is IBinaryStorable binary)
                return await Task.FromResult(binary.BinaryData.ReadAllBytes());
        }

        return null;
    }

to

    public async Task<byte[]> GetImage(object id)
    {
        var content = ContentRouteHelper.Service.Content;
        if(content == null)
                throw new HttpException(404, $"No image exists at {id.ToString()}");
        if (content.QueryDistinctAccess(AccessLevel.Read))
        {
            if (content is IBinaryStorable binary)
                return await Task.FromResult(binary.BinaryData.ReadAllBytes());
        }

        return null;
    }

**Comment by vnbaaij** [comment]
Thanks for this. I'll make sure it gets applied in the next version
