### ISSUE TITLE
UNC Doesn't work

### ISSUE THREAD

**Issue by Sebbe** [vnbaaij/ImageProcessor.Web.Episerver#15]
While fixing issue #9 you brought back the error from issue #5 so UNC path doesn't work anymore if you only set the path in basePath.

The fix is the same as for issue #5 

https://github.com/vnbaaij/ImageProcessor.Web.Episerver/blob/b93b911d347ee017abe23984d2f6daff3430d2d6/src/ImageProcessor.Web.Episerver/FileBlobCache.cs#L100
should be:
`string basePath = (EPiServerFrameworkSection.Instance.AppData.BasePath.IndexOf(@"\\") == 0)`

**Comment by vnbaaij** [comment]
Fixed in 5.0.1. Thanks!
