### ISSUE TITLE
'ImageProcessor.Web.Caching.CachedImage ImageProcessor.Web.Caching.CacheIndexer.Add(ImageProcessor.Web.Caching.CachedImage, System.TimeSpan)'.

### ISSUE THREAD

**Issue by scottreed** [vnbaaij/ImageProcessor.Web.Episerver#2]
I have installed this on the Episerver Alloy Demo as I'm looking to move away from ImageResizer in our solutions due to the poor caching support but got the error when going directly to the image path generated

`'ImageProcessor.Web.Caching.CachedImage ImageProcessor.Web.Caching.CacheIndexer.Add(ImageProcessor.Web.Caching.CachedImage, System.TimeSpan)'.`

I have checked and the web.config and config folder files have been created?

**Comment by vnbaaij** [comment]
Please make sure you have updated all packages to the latest version. Let me know if that helps.

**Comment by ErikHen** [comment]
It helps if you update the ImageProcessor packages to latest version. Is there a mismatch between the version of ImageProcessor.Web.Episerver and the required version of ImageProcessor packages?

**Comment by vnbaaij** [comment]
Yes, there was a mismatch. I updated the packages (both for Episerver 10 and 11) to depend upon the latest ImageProcessor packages. The new packages have been submitted to the Episerver NuGet feed so should be available soon.

**Comment by scottreed** [comment]
Thanks I have tested this now and updated and everything works as expected
