### ISSUE TITLE
Using WebP format option

### ISSUE THREAD

**Issue by KuulArt** [vnbaaij/ImageProcessor.Web.Episerver#24]
Hi,

I have been trying to get webp working using the HtmlHelper method. But it seems that the previously used method Format(string) is obsolete and the new one using ImageFormat enum does not contain the WebP entry.

Is there any reason why the enum lacks this entry?

**Comment by vnbaaij** [comment]
No, no reason. Just an oversight. Will add it to the enum and release an update soon.
This will have to wait though for the VS2019 version of the Episerver Visual Studio Extension to be released as that is now the only version of VS installed on my machine

**Comment by vnbaaij** [comment]
Don't actually need the extension. Pushing update to the NuGet feed now
