### ISSUE TITLE
FileBlobCache: 'VirtualCachePath' is not a valid virtual path.

### ISSUE THREAD

**Issue by KuulArt** [vnbaaij/ImageProcessor.Web.Episerver#25]
I am getting an error when I set `<appData basePath="C:\something" />` to an absolute path.
It seems that for some reason the "VirtualCachePath" is not being read correctly from Web.Config and then it tries to use basePath incorrectly.
This can be reproduced by changing appData basePath to an absolute path.

**Comment by vnbaaij** [comment]
Thanks for reporting this.

Fixed in Imageprocessor.Web.Episerver 5.3.2. Submitted it to the feed so should be available shortly.
