### ISSUE TITLE
Random HTTP 403 Server failed to authenticate the request issues

### ISSUE THREAD

**Issue by kmukku** [vnbaaij/ImageProcessor.Web.Episerver#26]
Hi! On DXC site we are having random 403 errors for some images. Errors come and go randomly. Error message remains the same, only time stamps change:

`
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:[removed] Time:2019-05-14T12:31:03.9442113Z
</Message>
<AuthenticationErrorDetail>
Signature not valid in the specified time frame: Start [Tue, 14 May 2019 11:41:46 GMT] - Expiry [Tue, 14 May 2019 12:01:46 GMT] - Current [Tue, 14 May 2019 12:31:03 GMT]
</AuthenticationErrorDetail>
</Error>
`

Before error arrives the original url get translated to this internal one:

https://[removed].blob.core.windows.net/epiblobs/[removed]/3p!_[removed].webp?sv=2017-04-17&sr=b&sig=[removed]&st=2019-05-14T11%3A41%3A46Z&se=2019-05-14T12%3A01%3A46Z&sp=r

Anyone else having this? Any ideas how to fix? DXC support washed their hands out of this.

**Comment by vnbaaij** [comment]
Hi,

Not seen this before. Are the errors always seen on .webp files? 

The rest of the url (after the filename) is what is called a Shared Access Signature (SAS) code. This allows access to the Azure blob storage. I configured the SAS to be valid from 5 minutes before the actual request till 10 after.  Can you check if the request time falls between the date/times mentioned in the st (starttime) and se (SAS expiry) parameters in the URL?

**Comment by kmukku** [comment]
Hi, 

At a moment all of these seems to be .webp files. From error you can see that request time (current and Time:) is 12:31 and it doesn't fall between defined start 11:41 and 12:01 expiry.

**Comment by vnbaaij** [comment]
Ok, so that explains the error  in a sense that the request is outside of the SAS validity window. Unfortunately  it does not explain **why** the request is outside that window.
Are you able to request the image with it's original url? 
Also can you check the ImageProcessor WebP plugin version installed?

**Comment by kmukku** [comment]
Yes, I'm able to request the image with it's original urls (both /link/[removed].aspx and Content.Url() works). Installed ImageProcessor.Plugins.WebP is 1.2.0.100.

**Comment by kmukku** [comment]
Ok, we got it figured out. Basically same issue as this one here:

https://github.com/JimBobSquarePants/ImageProcessor/issues/178

I was missing StreamCachedImage=true setting on environment which uses CDN. This caused CDN to cache 302 response for 20 minutes instead of the actual image for 120 minutes. Image worked for 15 minutes and was broke for 5 minutes to be fine again for next 15 minutes because blob signature validity is set for -5 - 15 minutes.

I hope this helps someone else who might run into same problem. :)

**Comment by vnbaaij** [comment]
Good you got it solved. Will look into it to see if I can get more consistent behavior between the StreamCachedImage modes

Vincent Baaij


________________________________

**Comment by nalinasanka** [comment]
Hi Vincent,

I'm facing same random 403 issue on DXC servers when it going to show the images in the site. I'm not using CDN cache, hence I set StreamCachedImage=false in my cache config.

403 Error response:
`<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ff91b0a1-e01e-0029-669f-dbef8d000000
Time:2020-02-04T21:08:32.0019309Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Tue, 04 Feb 2020 20:46:01 GMT] - Expiry [Tue, 04 Feb 2020 21:06:01 GMT] - Current [Tue, 04 Feb 2020 21:08:32 GMT]</AuthenticationErrorDetail></Error>
`


DXC Cache Config:
```<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="EpiserverAzureBlobCache">
  <caches>           
    <cache name="EpiserverAzureBlobCache" type="ImageProcessor.Web.Episerver.Azure.AzureBlobCache, ImageProcessor.Web.Episerver.Azure" maxDays="20">
      <settings>
        <setting key="StreamCachedImage" value="false"/>        
      </settings>
    </cache>
  </caches>
</caching>
```

We done a production deployment with Episerver Image Processor yesterday and seen those 403 errors in our live site. Did I missing any config here? Could you please help me to solve this issue?

Thanks

**Comment by vnbaaij** [comment]
Hi Nalin, 

As you can see in the error response, the request is outside of the SAS validity window. I have no clue on why that is happening. Only thing I can advise at this time is to try it with the StreamCachedImage=true setting

**Comment by nalinasanka** [comment]
Hi Vincent,

The property "StreamCachedImage=true", doesn't it applicable only for CDN ? Because I'm not using CDN for Image cache with my site, so I set it as "false".

Thanks

**Comment by vnbaaij** [comment]
True, but I *think* it eorks without cdn as well. Been a while since I worked on this

**Comment by nalinasanka** [comment]
Hi Vincent,

I changed that config as "StreamCachedImage=true" and deployed to DXC environment (Pre-Production). Now I can see following response with "webp" type.

![image](https://user-images.githubusercontent.com/8293984/73799658-68ee8380-481b-11ea-9366-1a3fb13a4e45.png)


Just want to check with you, am I getting correct response with that setting?

Thank you

**Comment by nalinasanka** [comment]
In addition now I cant see images start with "3p!_" prefix, is that correct behavior with that setting.

Thanks

**Comment by vnbaaij** [comment]
3p!_ extension means you are getting a file from the cache, so that seems ok. Response look good as well, I think. I would suggest to test with these settings for a couple of days to see if you don't get any 403's anymore.

**Comment by nalinasanka** [comment]
Hi Vincent,
Does that mean, those images are not cache now after set "StreamCachedImage=true"? Right now we are having a Production issue with 403 errors and we want to send a fix for it soon. 

So you advice highly valuable at this stage.
Thank you

**Comment by vnbaaij** [comment]
If you don't see the 3p!_tags, then the images are not coming from the cache. 

The problem seems to be tied to the usage of webp. This was also the case with the original poster of this issue. Maybe you can test with original StreamedCacheImage=false setting AND not use webp?
