### ISSUE TITLE
Resize mode in Picture-element

### ISSUE THREAD

**Issue by tuube** [vnbaaij/ImageProcessor.Web.Episerver#27]
Hello. Is there a way to change the resizing mode when using the picture-helper?
I have a need to use the min-mode, so that images don't get upscaled if they happen to be small.

And thanks for creating this awesome helper for us Episerver-developers :)

**Comment by vnbaaij** [comment]
Hi,

Sorry for the late reply, crazy busy.

The `PictureHelper.Picture` method has an overload that takes an `UrlBuilder` as a parameter for the image. The `UrlBuilder` has an extension method for Resize in which you can specify the `ResizeMode`. The `ResizeMode` is an enumeration that contains all the ImageProcessor supported resize methods. The one you are looking for is `ResizeMode.Min`
