### ISSUE TITLE
.gif file becoming larger on resize and taking a long time to process

### ISSUE THREAD

**Issue by tuube** [vnbaaij/ImageProcessor.Web.Episerver#28]
Resizing one .gif file form the original 1200px width to 1000px width is taking multiple minutes to do, and the resulting file size becomes 2.6MB, when the original is 630KB. The file in question is attached here.

Is this working as it should? And if it is, is there any way to skip processing for .gif files entirely?

![noteeratut_osak](https://user-images.githubusercontent.com/19163063/63077392-d098d580-bf40-11e9-946c-5248eb3c91a3.gif)

**Comment by vnbaaij** [comment]
Must be something with it being an animated gift. Anyway it is a problem with the underlying ImageProcessor module (the resizing does not actually take place in my module). Although it is more or less in maintenance mode now, you might try raising an issue in the ImageProcessor repo.
