### ISSUE TITLE
Resizing causing high memory usages on app instance causing restarts

### ISSUE THREAD

**Issue by Arvlun** [vnbaaij/ImageProcessor.Web.Episerver#29]
Hello, Im trying to use this package in a DXC-solution but am having a problem with it causing high usage of memory and on the application process and causing the application process to restart. The effect being that when a user visits a page with alot of resized images (a gallery page) the TTFB times crawl upwards of 100 seconds and after that resulting in a 524 error from cloudflare CDN.

Normal pages which only has a few resized images seems to be loading fine, though.

I was having the same issue with ImageResizer and got recommended trying this by episerver support. ImageResizer had the exakt same problem. The packages seems to be having no problem in my local enviroment though.

Episervers input was that:
"In local environment, they use physical disk to cache images for processing while in Azure, they have to use Blob Storage. I may assume that: on the performance standpoint, Azure Blob Storage is slower than physical disk."

Has anyone had a similar issue? Or even has anyone had a working resizer in a DXC solution?

**Comment by vnbaaij** [comment]
Hi, Blob will certainly be slower than disk access. But that is probably not the problem. Judging from what you've described, my guess is that that the images that you are trying to resize somehow trip up the resizer modules (ImageProcessor in this case). Unfortunately there is not a lot I can do about that. I just facilitate an easy way to call the ImageProcessor from Episerver.
You could try to open an issue in that repo. Also make sure that you are using the image cache

**Comment by ErikHen** [comment]
Hi. This site is hosted on DXC-S, and this particular page has more than 200 resized images: https://www.nord-lock.com/insights/
However, most images are lazy-loaded. But I have not experienced any issues that you describe.

**Comment by Arvlun** [comment]
Thanks for your fast replies. I have since tested a bit more and it seems that using this package the caching of the resized images seems to work. Using ImageResizer the problem occured every time the page loaded since, I assume, the resized images wasn't cached in the blob-storage.

I'll look into lazy-loading the images to see if we could implement that to help with the initial resizing of the images. Thanks!

**Comment by Arvlun** [comment]
Hello again, it seems like the image
