### ISSUE TITLE
Does not support multi site

### ISSUE THREAD

**Issue by chrno1209** [vnbaaij/ImageProcessor.Web.Episerver#3]
Hi Vincent,
When running on project with multi sites, siteassets images always fail to resize.
This is because in ImageProcessor.Web.Episerver.Azure.ImageService, you use UrlResolver to get the content but the id is only relative path, which will return null on siteassets content.

Is there any chance you can check it please?

Regards,
Hieu.

**Comment by vnbaaij** [comment]
Hi Hieu,

I see what you mean. Do you happen to know how to fix it. In the ImageService code I don't have a HttpContext. How can I get an absolute path?

**Comment by chrno1209** [comment]
Hi Vincent,
Thanks so much for your reply, I also posted a question here https://github.com/JimBobSquarePants/ImageProcessor/issues/668 to ask the owner of ImageProcessor on how to access HttpContext in IImageService.

Also, I have found a work around to fix the issue by modifying [EpiserverImageProcessingModule](https://github.com/vnbaaij/ImageProcessor.Web.Episerver/blob/master/src/ImageProcessor.Web.Episerver/EpiserverImageProcessingModule.cs)

```
        protected override string GetRequestUrl(HttpRequest request)
        {
            string requestUrl = request.Url.AbsoluteUri;

            ...
        }
```

It would be great if you can test and release a fix on Nuget :).
I am using it in Epi 10 project.

Again, thanks so much for your time on making this great package.

**Comment by vnbaaij** [comment]
Hi Hieu,

I tested your workaround and can confirm it works on my CMS 11 version. The fix is so general that I believe I works on CMS 10 also. I created new packages and uploaded them to the feed. They should be available somewhere in the coming days.

Hope this helps,

Vincent

**Comment by chrno1209** [comment]
Hi Vincent,
Thanks for your work, I will ask Episerver Nuget Team to approve it ASAP :).

Regards,
Hieu.

**Comment by chrno1209** [comment]
Hi, just want to inform you that your package was approved and available on the feed now :).
Cheers.

**Comment by ludwi** [comment]
Hi, 

Posting here instead of creating a new issue since it's related. 

When we're using this package on an installation with more than one site with site-specific assets checked no images are being cropped except for the site with a wildcard hostname. Images placed in the globalassets folder are working though. We're using the latest version of everything. 

Any idea how this can be resolved or if we need to do any special configuration for this case? 

Thanks!
