### ISSUE TITLE
Support for ImageProcessor PostProcessor Plugins

### ISSUE THREAD

**Issue by kapelletier** [vnbaaij/ImageProcessor.Web.Episerver#31]
Hey there... more of a question than an issue. I installed this nuget package: [ImageProcessor.Web.Plugins.PostProcessor](https://imageprocessor.org/imageprocessor-web/plugins/postprocessor/)

It does not appear to be doing anything by way of optimizing images coming out of the cache, which is what it can do for certain image types.

Before I look closer, was wondering if this should "just work" with ImageProcessor.Web.EpiServer?

Those postprocessor docs indicate that "Once installed, the plugin requires no further configuration."

Any thoughts would be great.

**Comment by vnbaaij** [comment]
Hi, sorry about the delayed response. I think it might have to do with me changing the caching path for the ImageProcessor. I do that in the FileBlobCache folder. I'm not in a position to be able to work on this at the moment. Hope you will be able to take a look yourself. Let me know if you find anything.
