### ISSUE TITLE
Azure DXC - What is the purpose of security.config file?

### ISSUE THREAD

**Issue by nalinasanka** [vnbaaij/ImageProcessor.Web.Episerver#32]
Hi,

We are going to use the ImageProcessor.Web.Episerver.Azure library with our CMS site and would like to know what is the purpose of each section in security.config file? (We assume it uses to control the security when the call happens). Please see the security.config file

```<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>        
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="4194304"/>
        <setting key="Timeout" value="3000"/>
        <setting key="Protocol" value="http"/>
      </settings>
      <whitelist>
      </whitelist>
    </service>
    <service name="AzureImageService" type="ImageProcessor.Web.Episerver.Azure.ImageService, ImageProcessor.Web.Episerver.Azure">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
      </settings>
    </service>
  </services>
</security>
```
We can see two services placed in this file and could some one explain what is the purpose of those?
- RemoteImageService
- AzureImageService

Thank you

**Comment by vnbaaij** [comment]
AzureImageService is where the actual service that is responsible for the image processing is declared. The RemoteImageService is a standard ImageProcessor functionality to make it possible to manipulate images that are not on the same server as the site (i.e. remote images) See https://imageprocessor.org/imageprocessor-web/configuration/#securityconfig for more information.
