### ISSUE TITLE
ImageProcessor.Web.Episerver.Azure is not compatible with latest EPiServer.Azure

### ISSUE THREAD

**Issue by burkovsky** [vnbaaij/ImageProcessor.Web.Episerver#33]
Hello,

Episerver has released new major version for `EPiServer.Azure` [package](https://nuget.episerver.com/package/?id=EPiServer.Azure). Could you please update `ImageProcessor.Web.Episerver.Azure` package to be compatible with latest `EPiServer.Azure`?

Thank you!

**Comment by vnbaaij** [comment]
I've just uploaded a new version (5.6) to the NuGet feed. Should be available shortly.
