### ISSUE TITLE
GetCropUrl makes the crop query using x and y offset instead of height and width

### ISSUE THREAD

**Issue by kristype** [vnbaaij/ImageProcessor.Web.Episerver#35]
I tried the crop functionality and found that my images were not cropped correctly.
I checked the crop documentation, and it looks like the width and height should be applied directly to the query and not the calculated x and y offset.

[https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/crop/](https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/crop/)

It looks like a super easy fix, and I can make a pull request for it.

**Comment by vnbaaij** [comment]
This has been fixed in V5.6. New NuGet has been uploaded to the feed. Should be available soon.
