### ISSUE TITLE
Exception in FileBlobCache.RewritePath

### ISSUE THREAD

**Issue by Towmeykaw** [vnbaaij/ImageProcessor.Web.Episerver#38]
Hi! I'm experiencing an error which seems to be originating in the FileBlobCache. I get the error "The remote host closed the connection. The error code is 0x800703E3", which seems to be because the user cancelled the request before it was finished and seems to be because of calling context.Response.End() in the RewritePath method. A similar issue was fixed in the main ImageProcessor library in this commit https://github.com/JimBobSquarePants/ImageProcessor/commit/657a29eef506796915cfaf9f193050160c318577

Please let me know if I can be of more assistance 😄

**Comment by vnbaaij** [comment]
I added the same Try/catch as James. Hope this fixes it. New version (5.6.3) submitted to the feed

**Comment by ErikJJonsson** [comment]
We still experience the same error in RewritePath but get a HttpException which is not handled by the added try-catch.
Could this be fixed?

**Comment by vnbaaij** [comment]
see #56
