### ISSUE TITLE
Cached images being rendered after a 302 redirect

### ISSUE THREAD

**Issue by sidu1987** [vnbaaij/ImageProcessor.Web.Episerver#39]
Hi Vincent,

I am seeing that the cached image is being rendered after a 302 redirect. I am testing this out on EPi Foundation and below is a screenshot for your reference:

https://www.screencast.com/t/q18QXQemD

I have installed the Azure plugin of the ImageProcessor since the client I am working for is using DXP. Below are the packages that are installed:
```
<package id="ImageProcessor" version="2.9.0" targetFramework="net472" />
<package id="ImageProcessor.Plugins.WebP" version="1.3.0" targetFramework="net472" />
<package id="ImageProcessor.Web" version="4.12.0" targetFramework="net472" />
<package id="ImageProcessor.Web.Config" version="2.6.0" targetFramework="net472" />
<package id="ImageProcessor.Web.Episerver" version="5.6.3.41017" targetFramework="net472" />
<package id="ImageProcessor.Web.Episerver.Azure" version="5.6.3.26563" targetFramework="net472" />
```
Below is the cache.config:

```
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="EpiserverAzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" browserMaxDays="7">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache"/>
      </settings>
    </cache>
    <cache name="EpiserverBlobCache" type="ImageProcessor.Web.Episerver.FileBlobCache, ImageProcessor.Web.Episerver" maxDays="365" browserMaxDays="7">
      <settings/>
    </cache>
    <cache name="EpiserverAzureBlobCache" type="ImageProcessor.Web.Episerver.Azure.AzureBlobCache, ImageProcessor.Web.Episerver.Azure" maxDays="365">
      <settings>
        <setting key="UseCachedContainerInUrl" value="true"/>
        <setting key="StreamCachedImage" value="false"/>
      </settings>
    </cache>
  </caches>
</caching>
```
Also the view that renders the thumbnails has the code mentioned below:

``@Html.Picture(Html.ProcessImage(Model.ImageUrl).Resize(null, null, ImageProcessor.Imaging.ResizeMode.Max), Foundation.Infrastructure.ImageTypes.Thumbnail, "img-fluid product-tile-grid__image", LazyLoadType.Native)``

Is this expected behavior?

**Comment by vnbaaij** [comment]
Well, I can't say if that is expected behavior in your situation. Are you (not) seeing things you are supposed to see? If so, you could experiment with the StreamCachedImage parameter.
I can't help you with testing this as I don't have an Episerver site and/or DXP environment at my disposal (I do not work at Episerver anymore)

**Comment by boat-priyanka-agrawal** [comment]
Hi @sidu1987 , I am also seeing the same behavior on my Episerver DXP environment. Were you able to find any way to stop these redirects? or is this fine?
