### ISSUE TITLE
Why are PNG's not converted to WEBP?

### ISSUE THREAD

**Issue by kdboer** [vnbaaij/ImageProcessor.Web.Episerver#40]
According to the WEBP library documentation here https://developers.google.com/speed/webp/?csw=1
PNG conversion to WEBP is supported.
This is also the library that the ImageProcessor.WEBP plugin uses, according to https://github.com/JimBobSquarePants/ImageProcessor/tree/release/3.0.0/src/ImageProcessor.Plugins.WebP

Then why is there an explicit check on fileextension .jpg on line 81 of 
https://github.com/vnbaaij/ImageProcessor.Web.Episerver/blob/master/src/ImageProcessor.Web.Episerver/Extensions/Picture/PictureUtils.cs
Before adding the WEBP sourcesets?

**Comment by vnbaaij** [comment]
Good question. @ErikHen any thoughts on this?

**Comment by ErikHen** [comment]
As far as I know the png -> webp conversion in imageprocessor can not be done lossless. Meaning that you would get grainy/blurry parts in an image, instead of the solid colors in the original png. 
In the absolute majority of cases you use the png format for it's lossless compression. Therefore I took the decision to not convert png images.

**Comment by vnbaaij** [comment]
Clear answer, thanks. So we considers this to be by design and are not going to change it

**Comment by ipoley-r7** [comment]
@vnbaaij / @ErikHen 

Would this be something that can be made optional in case lossy compression is acceptable? Given the file size savings, it seems like a worthwhile option to add.

**Comment by ErikHen** [comment]
Yes, making it an option is pretty easy. There are a couple of other things I'd like to add anyway. Might be able to squeeze it in, in the next week or so.
I did take a look at the source for ImageProcessor, and it seems to have possibility to create lossless WebP images, but not sure yet if ImageProcessor.Web can manage it.

**Comment by vnbaaij** [comment]
A 5.8.0 version has been pushed to the NuGet Feed. See the readme for the enhancements Erik 🥇 made.
