### ISSUE TITLE
ResizeCrop centerX and centerY are flip and float ToString is not CultureInvariant

### ISSUE THREAD

**Issue by AlexanderSeel** [vnbaaij/ImageProcessor.Web.Episerver#41]
Hi,

we tried to use the ResizeCrop Method for Focal Point.

First we realized that centerX and centerY is set in the url as center=x,y but expected center=y,x

Second the x and y will in the url for example center=0,4,0,5 depended on the Culture of the server in our case german.

Kind regards

Alexander Seel

**Comment by ErikHen** [comment]
Hi Alexander. Can you provide a code snippet to clarify?
Thanks

**Comment by AlexanderSeel** [comment]
We used for example following call 
`@Html.ProcessImageWithFallback(Model.Image.ContentLink, string.Empty).ResizeCrop(400, 300,0.2f,0.4f)`

**Comment by AlexanderSeel** [comment]
Thanks for your fix

**Comment by vnbaaij** [comment]
V5.6.4 is uploaded to the feed. Should be live soon
