### ISSUE TITLE
Focal point not respected when using the PictureHelper

### ISSUE THREAD

**Issue by bauwie** [vnbaaij/ImageProcessor.Web.Episerver#43]
When using the ImagePointEditor the PictureHelper doesn't apply the focal point if the image-url is used in the view (see below for example).

`@Html.MyPicture(Url.ContentUrl(Model.CurrentContent.PageImage), new ImageType
            {
                DefaultImgWidth = 750, HeightRatio = 1,
                SrcSetWidths = new[] { 375, 750, 980, 1500 },
                SrcSetSizes = new[] { "(max-width: 980px) calc((100vw - 40px))", "(max-width: 1200px) 368px", "750px" }
            })`

A similar call, using the ContentReference works just fine

`
@Html.MyPicture(Model.CurrentContent.PageImage, new ImageType
            {
                DefaultImgWidth = 750, HeightRatio = 1,
                SrcSetWidths = new[] { 375, 750, 980, 1500 },
                SrcSetSizes = new[] { "(max-width: 980px) calc((100vw - 40px))", "(max-width: 1200px) 368px", "750px" }
            })
`

**Comment by ErikHen** [comment]
Hi! That is correct. A reference to the image object is needed to fetch the focal point, since the focal point is stored in a property on the image object. 
Same goes if storing an alt-text on the image object. 
I guess this could be made more clear in the documentation...
