### ISSUE TITLE
Tint method hex code issue

### ISSUE THREAD

**Issue by endamcnamee** [vnbaaij/ImageProcessor.Web.Episerver#44]
When using the ImageProcessor.Web.Episerver.UI.Blocks processing Tint method, the URL is generated with a "#" in the hex code. The processor does not handle this. Suggest replacing "#" with an empty string in the UrlBuilderExtensions.cs "UrlBuilder Tint(this UrlBuilder target, string color)" method or maybe safer in the ImageProcessor.Web.Episerver.UI.Blocks.Models.Blocks.TintBlock GetMethod.

**Comment by vnbaaij** [comment]
Version 5.6.5 fixes this in the UrlBuilder and is pushed to the feed
