### ISSUE TITLE
Time taken to download the image has increased after rendering using Picture html helper

### ISSUE THREAD

**Issue by Anish-Peethambaran** [vnbaaij/ImageProcessor.Web.Episerver#45]
Although the image size has reduced, the time taken to download the webp version of the image has increased as compared to the earlier jpg version. Is there anything we are missing here. Attaching the screenshot and code snippet.

 @Html.Picture(Url.ContentUrl(Model.BackgroundImage), ImageTypes.HeroImage)

![ImageProcessor_Issue](https://user-images.githubusercontent.com/54981074/101902328-63379c00-3baa-11eb-9cde-39ea673b19c8.jpg)

**Comment by vnbaaij** [comment]
Hi,
I'm afraid I can't do much about that. This is  an effect that sometimes shows up with processed images. Might be something with that has to do with quality settings of the conversion.
