### ISSUE TITLE
image load time on processed image in DXP

### ISSUE THREAD

**Issue by dxred-yagnik** [vnbaaij/ImageProcessor.Web.Episerver#46]
Hey Vincent

I am using this plugin in DXP to improve image loading performance to resize image at rendering time using ProcessImage helper as per small thumbnail dimension to avoid loading of big size image.

I noticed original image 900x506 size 55 kb and taking 500 ms to load, while using ProcessImage helper with ?width=380 its size reduced to 22 kb but load time increased to 700 ms.

As image size reduced I was expecting to reduce load time even thought azure blob cache is enable, in following request still load time remain same 700 ms.

Can you help what was wrong?

**Comment by vnbaaij** [comment]
One thing you could look at is if the cache is (not) working correctly. Are you storing the images in Azure blob storage? I. E. Did you install the ImageProcessor.Web.Episerver.Azure plugin? 
If misconfigured, the images get stored on the app service server and that can be slower as well

**Comment by dxred-yagnik** [comment]
Hi Vincent

 

Thanks for quick revert.

 

Yes Episerver Azure nuget is installed and cache.config is also set correctly.

 

I can see processed images stored on azure blob using storage explorer in same guid folder with prefix 3p!_

 

Regards,

 

Yagnik Jadav

Founder, CEO, Episerver Certified Developer

 

mobile  <tel:+919870462838> +91 98704 62838 | skype  <skype:yagnik_v_jadav> yagnik_v_jadav

 <http://www.dxred.com/> www.dxred.com | digital experience redefined

 

Offshore Episerver Development Center in India.

 



Implementation | Staffing | Consultancy

**Comment by vnbaaij** [comment]
Sorry, no idea then what might be causing this

**Comment by dxred-yagnik** [comment]
Hi Vincent

 

You can close this, its working on Azure.

 

Regards,

 

Yagnik Jadav

Founder, CEO, Episerver Certified Developer

 

mobile  <tel:+919870462838> +91 98704 62838 | skype  <skype:yagnik_v_jadav> yagnik_v_jadav

 <http://www.dxred.com/> www.dxred.com | digital experience redefined

 

Offshore Episerver Development Center in India.

 



Implementation | Staffing | Consultancy
