### ISSUE TITLE
Use of ImageProcessor package for live site

### ISSUE THREAD

**Issue by Anish-Peethambaran** [vnbaaij/ImageProcessor.Web.Episerver#47]
We have tested the package and planning to have this deployed to production. But since this is not a Episerver verified/certified package we thought of ensuring that it is safe to use from a security perspective. Could you please comment on this?

**Comment by vnbaaij** [comment]
Hi,
As I am the author, I might not be the best person to judge the security of the packages. However, the only thing the packages do is alter images which are already being published on a site. The is no information being written back to Episerver. The fact that it has 150k+ downloads (and 86k+ for the Azure part) speaks for the package, I think.
If you need more confirmation, I would suggest to have a security expert take a look at the source code for both my packages as the underlying ImageProcessor packages (that have even way more downloads). It is all open source, so anyone can poke at the code as much and as deep as they want.
Hope this helps.

**Comment by jonascarlbaum** [comment]
...and EPiServer uses it on Alloy-site and Foundation...

See https://github.com/episerver/foundation-mvc-cms/blob/develop/src/Foundation/packages.config as a reference.

Guess it all speaks for the package I guess...

**Comment by vnbaaij** [comment]
To be fair (and transparent), I added it to the Alloy site myself when I worked at Episerver 😁

**Comment by jonascarlbaum** [comment]
Hehe, I remember that I've saw your name in the Alloy-repo some years ago... ;)
