### ISSUE TITLE
Updated images in Assets Pane doesn't clear cache for that image, so old image is still served.

### ISSUE THREAD

**Issue by jonascarlbaum** [vnbaaij/ImageProcessor.Web.Episerver#48]
Hi, we have an issue on a customers new site _(first production deploy tomorrow)_, where they updated an image _(uploaded the same image with the same name)_.

The result is that they got **the old image served**. It's completely logical, of course... ;) 

However, the expected behaviour should be that any cached items based on an Asset (with a specific `ContentReference.ID`) is cleared on updates, so all new requests to those images that pass `ImageProcessor` would trigger new resizes and cached images.

By the way, we are using the `ImageProcessor.Web.Episerver.FileBlobCache` a.k.a. `EpiserverBlocCache` standard configured, the `DiskCache` is still in the config, but `currentCache`  says we're using `EpiserverBlobCache`.
```
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="EpiserverBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" memoryMaxMinutes="1" browserMaxDays="7">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache"/>
      </settings>
    </cache>
    <cache name="EpiserverBlobCache" type="ImageProcessor.Web.Episerver.FileBlobCache, ImageProcessor.Web.Episerver" maxDays="365" browserMaxDays="7">
        <settings/>
    </cache>
  </caches>
</caching>
```

Is there anything we've missed in configuration or is there any method we could call to **clear the cache** for a specific Asset, or is this something that could be built-in, maybe configurable in `cache.config` if this isn't something that everyone wants? ;)

**Comment by jonascarlbaum** [comment]
Ping @vnbaaij ;)

**Comment by vnbaaij** [comment]
Hi, I don't think there is anything missing in your config. I'm unfortunately not able to work on this anytime soon.
Maybe it helps if they delete the image first and then reupload?

**Comment by jonascarlbaum** [comment]
Yep, it works. But I guess it will happen occasionally and a cache-invalidation on content-updates would be a really nice feature. 😉

**Comment by vnbaaij** [comment]
I'll put in on the ToDo list. Thanks.

**Comment by jonascarlbaum** [comment]
Great! 👍

**Comment by ErikHen** [comment]
It is probably possible to invalidate the cache on the server for this use case. But the image may still be cached in e.g. CDN and browser (resized or not). If you really need to support this use case you need to change the file name when the same file is uploaded, or add a unique query string for every image version. 
Easiest solution is to teach editors to not upload with the same file name 😀.

**Comment by jonascarlbaum** [comment]
Yes, that is a possible workaround, maybe it’s even possible to override path on `MediaData`, to add version on path on content events, keeping filename so editors think it works as normal? Given that `MediaData` has the part stuff `PageData` has? 👍😉

I’m on the run now, so had to brainstorm on iPhone... 😂
