### ISSUE TITLE
UNC path error

### ISSUE THREAD

**Issue by larswp** [vnbaaij/ImageProcessor.Web.Episerver#5]
line 93 in FileBlobCache:
string basePath = (EPiServerFrameworkSection.Instance.AppData.BasePath.IndexOf("@\\\\") == 0)
should be:
string basePath = (EPiServerFrameworkSection.Instance.AppData.BasePath.IndexOf(@"\\\\") == 0)

**Comment by vnbaaij** [comment]
Good catch!

New versions (1.1.1 and 2.1.1) with fix uploaded to the Episerver NuGet feed
