### ISSUE TITLE
ImageReferenceList not working

### ISSUE THREAD

**Issue by johnligt** [vnbaaij/ImageProcessor.Web.Episerver#51]
In an Episerver project we switched the imagecropper from ITMeric to ImageProcessor.Web.Episerver

We now run into the problem that the ImageReferenceList is not working anymore.

I've also tested this in an Alloy project, but the ImageReferenceList was also not working in the Alloy project.

When you start dragging an image you get this message in the console:

Uncaught TypeError: Cannot read property 'defaultCheckAcceptance' of undefined
    at Object._checkAcceptance (ImageReferenceListSelector.js:179)
    at Object.checkAcceptance (dojo.js:15)
    at Object.onDndStart (widgets.js:2)
    at _24e.<anonymous> (dojo.js:15)
    at _24e._264 [as on/dnd/start] (dojo.js:15)
    at Function.on.emit (dojo.js:15)
    at Function.on.emit (dojo.js:15)
    at _24e.emit (dojo.js:15)
    at Object.publish (dojo.js:15)
    at Object._22a.<computed> [as publish] (epi.js:2)

The _source variabele is null.

The syntax used in the model class is:
        [Display(
            Name = "Vierkante afbeeldingen",
            Order = 20)]
        [ImageReference(CropRatio = 1d, AllowedTypes = new[] { typeof(ImageFile) })]
        public virtual ImageReferenceList Images { get; set; }

Are we doing something wrong, or does the ImageReferenceList just not work with ImageProcessor.Web.Episerver ?

**Comment by vnbaaij** [comment]
The offending line in `ImageReferenceListSelector` uses `_source` which is not defined. This is the same as it was in ITMeric's version. What I tried in my local test environment is that that line just does a `return true;` I think this is a viable solution as looking at `this.allowedDndTypes` returns `alloysample.models.media.imagefile` in the browser console. That value comesfrom the attribute you supply to the property in it's definition: `[ImageReference(CropRatio = 1d, AllowedTypes = new[] { typeof(ImageFile) })]`. Drag and drop is therefore automatically limited to the filetypes defined in `ImageFile`. Here through the `MediaDescriptor` attribute: `[MediaDescriptor(ExtensionString = "jpg,jpeg,jpe,ico,gif,bmp,png")]`

I cannot drag and drop files other than the mentioned types in the list. 

Might not be the cleanest or best solution, but this is as far as my javascript skills go,

A new version (5.6.4.25772) is uploaded to the NuGet feed and is also available from the releases page here (under latest release)
