### ISSUE TITLE
Getting 404 dependency errors for images after switching to azure blob cache

### ISSUE THREAD

**Issue by boat-priyanka-agrawal** [vnbaaij/ImageProcessor.Web.Episerver#54]
Hi,
We recently switched from EpiserverBlobCache to AzureBlobCache for images using imageprocessor. Since then, we are seeing **high number of dependency calls related to Azure blob: HEAD {environment name}  are giving 404.** 
Images are rendering fine on the site. We are just getting high dependency errors in Application Insight.

Below are the configs we have added -

**Cache config -**

![image](https://user-images.githubusercontent.com/70316089/126494773-68414086-567f-48f5-b836-205b78e30259.png)

**Security config**

![image](https://user-images.githubusercontent.com/70316089/126494657-0695067f-7312-4a28-9deb-d57a14326bc4.png)

**Is there any way to avoid dependency requests 404s?** 

Version no of image processor packages - 

ImageProcessor version="2.9.1" targetFramework="net471" 
ImageProcessor.Plugins.WebP version="1.3.0" targetFramework="net471" 
ImageProcessor.Web version="4.11.0" targetFramework="net471" 
ImageProcessor.Web.Config version="2.6.0" targetFramework="net471"
ImageProcessor.Web.Episerver version="5.6.0.29590" targetFramework="net471" 
ImageProcessor.Web.Episerver.Azure version="5.6.3.26563" targetFramework="net471"

**Comment by vnbaaij** [comment]
Hi,

I see you ImageProcessor.Web.Episerver is not the latest (5.6.5.15612). I suggest upgrading to that one first

**Comment by boat-priyanka-agrawal** [comment]
Hi @vnbaaij ,We have updated the packages and tested again. But are still seeing the dependency 404s. These are our current versions -
ImageProcessor" version="2.9.1" targetFramework="net471" 
ImageProcessor.Plugins.WebP" version="1.3.0" targetFramework="net471"
ImageProcessor.Web" version="4.12.0" targetFramework="net471" />
ImageProcessor.Web.Config" version="2.6.0" targetFramework="net471" 
ImageProcessor.Web.Episerver" version="5.6.5.15612" targetFramework="net471" 
ImageProcessor.Web.Episerver.Azure" version="5.6.3.26563" targetFramework="net471"

**Comment by boat-priyanka-agrawal** [comment]
@vnbaaij Adding more information here , I am sharing the sequence of the dependency calls that are getting executed.
As you can see, the call first checks if the blob exists or not, and that I think gives the 404. Then if the blob is not found, it creates a cached image in blob through PUT request, and then serves it in the end.  This, we think is causing the high no of dependency failures since our site contains a lot of images. How can we avoid such 404s? Or is there some other reason that these 404s are coming?

![image](https://user-images.githubusercontent.com/70316089/126513517-9eb5cb84-de54-4ae0-bc04-e3f6ec571ba8.png)

**Comment by vnbaaij** [comment]
So you are only getting the 404 when a processed image does not exist yet? If so, then I don't think anything can be done about that.

Met vriendelijke groet,

Vincent Baaij

**Comment by vnbaaij** [comment]
Closed due to inactivity
