### ISSUE TITLE
404 for ImageReferenceSelector.js

### ISSUE THREAD

**Issue by LindebergC** [vnbaaij/ImageProcessor.Web.Episerver#55]
1/ Install fresh alloy tech site
2/ Install ImageProcessor.Web.Episerver.UI.Crop from nuget
3/ Add to startpage.cs
[Display(GroupName = Global.GroupNames.Default)]
public virtual ImageReference TestImage { get; set; }
4/ Browse editmode all properties 

5/ 404 for  /EPiServer/Shell/11.25.0/ClientResources/ipepiuicrop/Editors/ImageReferenceSelector.js

**Comment by vnbaaij** [comment]
I've changedthe path in V5.7.0. Let me know if that fixes this.
