### ISSUE TITLE
.net core support?

### ISSUE THREAD

**Issue by barteksekula** [vnbaaij/ImageProcessor.Web.Episerver#59]
Is it possible to make it available for .net5?
Great work btw!

**Comment by vnbaaij** [comment]
Hi Bartosz, Unfortunately ImageProcessor is now in maintanace mode and only runs on .NET Framework. For .NET 5 and up there is now ImageSharp (from the same author). I published an limited early version of an Optimizely 'shell': https://nuget.optimizely.com/package/?id=Baaijte.Optimizely.ImageSharp.Web

**Comment by ErikHen** [comment]
You can also take a look at [https://github.com/ErikHen/PictureRenderer.Optimizely](https://github.com/ErikHen/PictureRenderer.Optimizely) if you are looking for the Picture helper functionality.

**Comment by barteksekula** [comment]
Thanks guys!
