### ISSUE TITLE
Support for CMS 12 / .NET5

### ISSUE THREAD

**Issue by jsalwen** [vnbaaij/ImageProcessor.Web.Episerver#61]
Is there a plan to add support for CMS 12 and .NET 5/6?

I am happy to contribute. I can create a branch `net5` with the code. But I don't want to start until I sync with you.

**Comment by ErikHen** [comment]
Hi. Please look at this for CMS 12 support: https://github.com/vnbaaij/ImageProcessor.Web.Episerver/issues/59
