### ISSUE TITLE
Cloudfront CDN support?

### ISSUE THREAD

**Issue by ipoley-r7** [vnbaaij/ImageProcessor.Web.Episerver#62]
Our production environment currently leverages Cloudfront to cache Episerver images. I know Azure blob storage requires additional configuration, but Is there any special configuration needed to support Cloudfront?

**Comment by vnbaaij** [comment]
Sorry, but I have no Cloud front experience. Think you can better ask this in the world forum

**Comment by ipoley-r7** [comment]
Understood. At the core of it, we're seeing the following error pop up only on production: 

> System.Web.HttpException (0x80004005): External component has thrown an exception

I'm having a very hard time at getting to the root error, but any ideas? Total shot in the dark but I'm assuming it is somehow related to Cloudfront, and potentially the modification of response headers?
