### ISSUE TITLE
CacheTrimmer Exception in Azure deployment environment 

### ISSUE THREAD

**Issue by harinarayanann** [vnbaaij/ImageProcessor.Web.Episerver#63]
Hi,
We are experiencing the below issue in Azure frequently and due to this the website crash's. 

`System.Threading.Tasks.Task.ThrowIfExceptional
System.Threading.Tasks.Task.Wait
ImageProcessor.Web.Caching.ImageCacheBase+CacheTrimmer.TimerRelease
System.Threading.ExecutionContext.RunInternal
System.Threading.ExecutionContext.Run
System.Threading.TimerQueueTimer.CallCallback
System.Threading.TimerQueueTimer.Fire
System.Threading.TimerQueue.FireNextTimers
---> (Inner Exception #0) Microsoft.WindowsAzure.Storage.StorageException
Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[[System.__Canon mscorlib]]
Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions+<>c__DisplayClass7.b__5
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
ImageProcessor.Web.Episerver.Azure.AzureBlobCache+<b__10_0>d.MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
ImageProcessor.Web.Caching.ImageCacheBase+CacheTrimmer+d__9.MoveNext
--- End of inner exception stack trace ---
---> (Inner Exception #1) System.Net.WebException
Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[[System.__Canon mscorlib]]
Microsoft.WindowsAzure.Storage.Blob.CloudBlob.b__33
Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[[System.__Canon mscorlib]]
--- End of inner exception stack trace ---
`

**Based on EPI suggestions**, I think we have to add the below config in the cache. config.

`<cache name="EpiserverAzureBlobCache"... trimCache="false" />`

**Below are our current config.**
`<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="EpiserverBlobCache">
  <caches>
    <cache name="EpiserverBlobCache" type="ImageProcessor.Web.Episerver.FileBlobCache, ImageProcessor.Web.Episerver" maxDays="7" browserMaxDays="7" />
  </caches>
</caching>`

**Current Transfermation config**
`<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="EpiserverAzureBlobCache" xdt:Transform="Replace" xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <caches>
    <cache name="EpiserverAzureBlobCache" type="ImageProcessor.Web.Episerver.Azure.AzureBlobCache, ImageProcessor.Web.Episerver.Azure" maxDays="7"  browserMaxDays="7">
      <settings>
        <setting key="StreamCachedImage" value="true"/>
        <setting key="CDNTimeout" value="1000"/>
      </settings>
    </cache>
  </caches>
</caching>`

Since I'm new for this Plugin, I'm not sure what is the right fix for the exception and if the EPI suggestions are right where should I add it?

Can anyone please help me to resolve this issue.

**Comment by vnbaaij** [comment]
According to your `caching.config`, you are not using the Azure Blobs cache....
This doesn't seem to be an issue with the code. Maybe you are better off asking for help on our

**Comment by harinarayanann** [comment]
Thank you for the quick response. Vincent
Yes, you are right, can you suggest me the right config settings, to make the plugin works DEV and Azure?

**Comment by vnbaaij** [comment]
Take a look here: https://github.com/vnbaaij/ImageProcessor.Web.Episerver/blob/master/samples/AlloySampleAzure/config/imageprocessor/cache.config

**Comment by harinarayanann** [comment]
Great, along with the above code if I add trimCache="false", do you think its correct config?

`<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="EpiserverAzureBlobCache">
  <caches>
    <cache name="EpiserverAzureBlobCache" type="ImageProcessor.Web.Episerver.Azure.AzureBlobCache, ImageProcessor.Web.Episerver.Azure" trimCache="false" maxDays="365">
      <settings>
        <setting key="StreamCachedImage" value="true"/>
        <setting key="CDNTimeout" value="1000"/>
      </settings>
    </cache>
  </caches>
</caching>`

**Comment by vnbaaij** [comment]
If you're using the Azure blob cache correctly (which should be the case with the config I linked), the trimCache should not have to be disabled. I think it gave errors for you because you are trying to use it on a file cache

**Comment by harinarayanann** [comment]
Ok Thank you, I'm not sure this error caused by file caching, Is there anyway I can eliminate files from cache, so that will help us to resolve the issue.
