### ISSUE TITLE
Custom blobcontainer for AzureBlobCache?

### ISSUE THREAD

**Issue by callebjernekull** [vnbaaij/ImageProcessor.Web.Episerver#72]
In current releases of AzureBlobCache, all cached images are stored in same blob as original image. That make it very hard to clear the cache if needed.

Maybe introduce a settingskey for providername like:
`string providerName = Settings.ContainsKey("blobprovidername") ? Settings["blobprovidername"] : EPiServerFrameworkSection.Instance.Blob.DefaultProvider;`

**Comment by vnbaaij** [comment]
Every generated image gets a prefix ('3p!_'). That way the automatic cleaner knows which files to delete and which not,
