### ISSUE TITLE
Images generated by the plug-in are greater than the actual image size

### ISSUE THREAD

**Issue by Anish-Peethambaran** [vnbaaij/ImageProcessor.Web.Episerver#85]
A 98 KB image was uploaded but while rendering, the image size is 158 KB. Attaching screen shot and code snippet. The expected image size should not be greater than 98KB.

 public static ImageType ArticleHeroImage { get; set; } = new ImageType
        {
            SrcSetWidths = new[] { 375, 750, 1920 },
            SrcSetSizes = new[] { "100vw" },
        };

@Html.Picture(Url.ContentUrl(Model.MainImageUrl), ImageTypes.ArticleHeroImage)

![RenderedImage](https://user-images.githubusercontent.com/54981074/193794113-436ba254-50e0-4e95-a887-4733a1946fff.PNG)

**Comment by vnbaaij** [comment]
Sorry, but this is not really a bug. There can be several reasons why this is happening. For example, the actual width of the Hero image is bigger than the original image. You can also try other formats and see if you get better results.
