### ISSUE TITLE
 System.InvalidOperationException: Target width 0 and height 0

### ISSUE THREAD

**Issue by Anish-Peethambaran** [vnbaaij/ImageProcessor.Web.Episerver#86]
In live site, a lot of http 500 errors are logged from ImageProcessor. The error says "System.InvalidOperationException: Target width 0 and height 0 must be greater than zero." But this is not raised during normal application usage as the image request URL are correctly formed. Errors are logged from wrongly formed URL like "https://www.abc.com/globalassets/new-website/privacy-policy/privacy-policy-banner.jpg?format=webp&width=1920|netstat&mode=crop&heightratio=0.5625&quality=80". I noticed the word "netstat" is getting added to the request URL! If I remove "netstat" ,the URL works fine. This malformed URL from unknown source is causing a lot of 500 errors being logged in production. Any help on this?

**Comment by Anish-Peethambaran** [comment]
> In live site, a lot of http 500 errors are logged from ImageProcessor. The error says "System.InvalidOperationException: Target width 0 and height 0 must be greater than zero." But this is not raised during normal application usage as the image request URL are correctly formed. Errors are logged from wrongly formed URL like "[https://www.abc.com/globalassets/new-website/privacy-policy/privacy-policy-banner.jpg?format=webp&width=1920|netstat&mode=crop&heightratio=0.5625&quality=80](https://www.abc.com/globalassets/new-website/privacy-policy/privacy-policy-banner.jpg?format=webp&width=1920%7Cnetstat&mode=crop&heightratio=0.5625&quality=80)". I noticed the word "netstat" is getting added to the request URL! If I remove "netstat" ,the URL works fine. This malformed URL from unknown source is causing a lot of 500 errors being logged in production. Any help on this?

There are also URL's logged in the format as given below which seems very strange.

![image](https://github.com/vnbaaij/ImageProcessor.Web.Episerver/assets/54981074/b699d5d9-2844-42b7-9cfe-9bd2d3507b66)

**Comment by vnbaaij** [comment]
Hi, I'm not actively maintaining this (very old) module anymore as I do not work for or with Optimizely anymore, I think you'll get better response when asking this at the [Optimizely ](https://world.optimizely.com/) community site.

**Comment by ErikHen** [comment]
That url is created using the picture helper(?), but I have no idea how those strange parameters are added. Is there something in your infrastructure that rewrites these urls?

**Comment by Anish-Peethambaran** [comment]
> That url is created using the picture helper(?), but I have no idea how those strange parameters are added. Is there something in your infrastructure that rewrites these urls?

Yes, I am using Html.Picture helper method to render picture element. There is no custom rewrite rules that would create those URL's.
