### ISSUE TITLE
v3 doesnt work with UNC paths

### ISSUE THREAD

**Issue by wiske80** [vnbaaij/ImageProcessor.Web.Episerver#9]
Hi Vincent,

i saw you post about the new version and your question that you were not sure about UNC paths working.

I tested it and can confirm that v3 doesnt work correctly with UNC paths. 

in the cache.config the setting `<setting key="VirtualCachePath" value="//<UNC PATH>" >` doesnt seem to do anything in this version and is being ignored. 

Instead it takes the  `<appData basePath="\\<UNC PATH TO BLOB>" />` of the web.config as the path, because it stores the cache files in the same folder as the blob. 

But what it does now is that it creates a new folder in your root with the name of the UNC Path and stores it there instead of going to the UNC path and storing it alongside the blob. 

For example let say the path is
` <appData basePath="\\diskstation-001\Media\Client" />`

It will create folders in your project root called "diskstation-001" -> "Media" -> "Client" -> and store the cache (!3p) files there. 

```
<caching currentCache="EpiserverBlobCache">
  <caches>   
    <cache name="AzureBlobCacheEpi" type="ImageProcessor.Web.Episerver.Azure.AzureBlobCache, ImageProcessor.Web.Episerver.Azure" maxDays="60">
      <settings>      
      </settings>
    </cache>    
    <cache name="EpiserverBlobCache" type="ImageProcessor.Web.Episerver.FileBlobCache, ImageProcessor.Web.Episerver" maxDays="365" browserMaxDays="7">     
    </cache>  
  </caches>
</caching>
```

security.config

```
<security>
  <services>    
    <service name="EpiserverImageService" type="ImageProcessor.Web.Episerver.ImageService, ImageProcessor.Web.Episerver"/>    
  </services>
</security>
```

**Comment by vnbaaij** [comment]
Vishal,

The UNC Path support is back in version 4.1! The cache.config setting `<setting key="VirtualCachePath" value="//<UNC PATH>" >` should be working again as expected.

If you could test and report back, that would be great.

**Comment by wiske80** [comment]
I can confirm that UNC path is working again in V4.1.. 

thanks for the awesome work Vincent.. i appreciate it!
